spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:com.fastcampus.boardserver.mapper/*.xml